name: auto-deploy-server

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write cloud storage credentials
        shell: bash
        env:
          CLOUD_STORAGE: ${{ secrets.CLOUD_STORAGE }}
        run: |
          echo "$CLOUD_STORAGE" > storagecredential.json

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tailoring-python:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop ${{ secrets.CNAME }} || true
            docker rm ${{ secrets.CNAME }} || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/tailoring-python:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tailoring-python:latest
            docker run -d \
              -p 80:8000 \
              -e APP_ENV=dev \
              -e DBUSER=${{ secrets.DBUSER }} \
              -e DBPASSWORD=${{ secrets.DBPASSWORD }} \
              -e DBHOST=${{ secrets.DBHOST }} \
              -e DBPORT=${{ secrets.DBPORT }} \
              -e DBNAME=${{ secrets.DBNAME }} \
              -e JWT=${{ secrets.JWT }} \
              -e GCP_CREDENTIAL=${{ secrets.GCP_CREDENTIAL }} \
              -e GCP_PROJECTID=${{ secrets.GCP_PROJECTID }} \
              -e GCP_BUCKETNAME=${{ secrets.GCP_BUCKETNAME }} \
              -e GCP_PATH=${{ secrets.GCP_PATH }} \
              --name ${{ secrets.CNAME }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/tailoring-python:latest
